
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: lbdr_development
  username: 'fouro'
  password: 'metallica2006'

test:
  <<: *default
  database: lbdr_development

production:
  <<: *default
  database: lbdr_development
  username:
  password:
