class RenameOldColumnToNewColumn < ActiveRecord::Migration[5.0]
  def up
    rename_column :banners, :description, :en_description    
    rename_column :sectors, :description, :en_description    
    rename_column :brands, :description, :en_description    
    rename_column :homes, :description, :en_description    
    rename_column :contents, :description, :en_description    
    rename_column :brand_banners, :description, :en_description    
    rename_column :group_banners, :description, :en_description    
    rename_column :investor_contents, :description, :en_description    
    rename_column :new_investments, :description, :en_description    
    rename_column :post_banners, :description, :en_description
    rename_column :board_members, :bio, :en_bio    
    rename_column :groups, :about, :en_about    
    rename_column :groups, :model, :en_model    
    rename_column :groups, :executive_committee_description, :en_executive_committee_description    
    rename_column :groups, :board_of_directors_description, :en_board_of_directors_description    
    rename_column :investors, :description, :en_description    
    rename_column :posts, :content, :en_content    
    rename_column :sector_banners, :description, :en_description
    rename_column :executives, :bio, :en_bio
    rename_column :groups, :spirit, :en_spirit
    rename_column :banners, :title, :en_title   
    rename_column :sector_banners, :title, :en_title
    rename_column :sectors, :name, :en_name    
    rename_column :brands, :name, :en_name   
    rename_column :homes, :title, :en_title   
    rename_column :contents, :title, :en_title
    rename_column :brand_banners, :title, :en_title   
    rename_column :group_banners, :title, :en_title   
    rename_column :investor_contents, :title, :en_title   
    rename_column :new_investments, :title, :en_title   
    rename_column :post_banners, :title, :en_title
    rename_column :board_members, :first_name, :en_first_name   
    rename_column :board_members, :last_name, :en_last_name   
    rename_column :board_members, :position, :en_position    
    rename_column :board_members, :governance_type, :en_governance_type   
    rename_column :executives, :first_name, :en_first_name
    rename_column :executives, :last_name, :en_last_name
    rename_column :investors, :firstname, :en_firstname
    rename_column :investors, :lastname, :en_lastname
    rename_column :posts, :title, :en_title    
    rename_column :posts, :author, :en_author
  end

  def down
    rename_column :sector_banners, :en_title, :title
    rename_column :banners, :en_description, :description    
    rename_column :sectors, :en_description, :description   
    rename_column :brands, :en_description, :description    
    rename_column :homes, :en_description, :description    
    rename_column :contents, :en_description, :description    
    rename_column :brand_banners, :en_description, :description    
    rename_column :group_banners, :en_description, :description    
    rename_column :investor_contents, :en_description, :description   
    rename_column :new_investments, :en_description, :description   
    rename_column :post_banners, :en_description, :description
    rename_column :board_members, :en_bio, :bio
    rename_column :groups, :en_about, :about   
    rename_column :groups, :en_model, :model   
    rename_column :groups, :en_executive_committee_description, :executive_committee_description   
    rename_column :groups, :en_board_of_directors_description, :board_of_directors_description
    rename_column :investors, :en_description, :description
    rename_column :posts, :en_content, :content  
    rename_column :sector_banners, :en_description, :description
    rename_column :executives, :en_bio, :bio
    rename_column :groups, :en_spirit, :spirit
    rename_column :banners, :en_title, :title  
    rename_column :sectors, :en_name, :name  
    rename_column :brands, :en_name, :name   
    rename_column :homes, :en_title, :title   
    rename_column :contents, :en_title, :title
    rename_column :brand_banners, :en_title, :title    
    rename_column :group_banners, :en_title, :title    
    rename_column :investor_contents, :en_title, :title    
    rename_column :new_investments, :en_title, :title    
    rename_column :post_banners, :en_title, :title
    rename_column :board_members, :en_first_name, :first_name   
    rename_column :board_members, :en_last_name, :last_name   
    rename_column :board_members, :en_position, :position   
    rename_column :board_members, :en_governance_type, :governance_type   
    rename_column :executives, :en_first_name, :first_name
    rename_column :executives, :en_last_name, :last_name
    rename_column :investors, :en_firstname, :firstname
    rename_column :investors, :en_lastname, :lastname
    rename_column :posts, :en_title, :title    
    rename_column :posts, :en_author, :author
  end
end
